### ISSUE TITLE
have to deploy IRC server

### ISSUE THREAD

**Issue by KiteFlyKid** [johnnywiller/IRC_botnet#1]
When I try to run IRCbotnet, do I have to deploy one of these IRC servers in my LAN as you've listed in the config？
```C
#define IRC_SERVERS "10.21.16.39:6667|127.0.0.1:6667|192.168.0.200:6667|172.17.0.5:6667|127.0.0.1:2222"
```

**Comment by johnnywiller** [comment]
Yes exactly, you need to have a IRC server running. You set whenever ip you
wish in the config and you can use the pipe | (or), in case you wanna have
multiple serves for failure protection.

Best regards.

**Comment by KiteFlyKid** [comment]
Thank you. And I wonder if  a common IRC server is OK ? Just like [Inspired IRC](https://ubuntu.com/tutorials/irc-server#3-download-source) 
Or I have to customize one

**Comment by johnnywiller** [comment]
Any irc server will be fine

**Comment by KiteFlyKid** [comment]
What's your IRC server? 
I tried several ones but failed to connect using your code.

**Comment by johnnywiller** [comment]
Have you put the right IP in the config file? Anyway, the server I was
using at the time was https://ngircd.barton.de/

**Comment by KiteFlyKid** [comment]
Yes I did.  And ngircd works! Thanks!
But different IRC servers' handshake vary(e.g. They may ask you to register after receiving NICK USER, or USER first and then NICK and other annoying things) . So I suffer a lot.
By the way, what's your **client irc app for C&C server to send command**? I use irssi  but when I type the command, it doesn't work as following
![image](https://user-images.githubusercontent.com/45324156/95860079-1f830a80-0d92-11eb-8c5d-9627423513e7.png)

**Comment by johnnywiller** [comment]
![Screenshot 2020-10-13 at 14 48 54](https://user-images.githubusercontent.com/5539939/95862489-49710880-0d63-11eb-84d2-f6703a637b23.png)
I was using IRSSI too, it's great. When you enter IRSSI, if you type
only @help, it doesn't work? You need at least 1 bot running. Like here
[image: Screenshot 2020-10-13 at 14.44.02.png]

**Comment by KiteFlyKid** [comment]
Thank u so much. 
And it finally works. I used to think that the msg should begin with "master" instead of using nick "master".
